# Generated by Django 5.2.3 on 2025-07-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaAM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escuelas',
            new_name='Escuela',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
